### ISSUE TITLE
Documentation on data sources

### ISSUE THREAD

**Issue by edward-io** [necsi/database#5]
Hi, I'm interested in using your dataset to perform some analyses. It would be very useful to have documentation to explain how the data is organized. I'm particularly interested in finding data that separates out community spread v/s infected travelers.

Thanks!

**Comment by bobbywlindsey** [comment]
Hey @edward-io. I'm working on automatically scraping multiple datasets and aggregating them for analysis. Part of this effort is also documenting what we have so far. You can see work in progress in the scrape-data-sources-#2 branch :)
